build: 
	gcc -Wall -g main.c -o /home/harzinn/coding/c/coursera/week4/bin/main_debug

win32:
	i686-w64-mingw32-gcc -Wall -g main.c -o /home/harzinn/coding/c/coursera/week4/bin/main_debug_win32.exe

win64:
	x86_64-w64-mingw32-gcc -Wall -g main.c -o /home/harzinn/coding/c/coursera/week4/bin/main_debug_win64.exe

run:
	./home/harzinn/coding/c/coursera/week4/bin/main_debug

clean:
	rm /home/harzinn/coding/c/coursera/week4/bin/*
