build:
	gcc -Wall -g main.c -o bin/main_debug

win32:
	i686-w64-mingw32-g++ -g main.c -o bin/main_debug_win32.exe

win64:
	x86_64-w64-mingw32-gcc -g main.c -o bin/main_debug_win64.exe

run:
	./bin/main_debug
